enabled: true

exclude:
  - '**/*.patch'
  - '**/node_modules/**/*'
  - '**/vendor/**/*'
  - '.github/workflows/**/*' # https://github.com/restyled-io/restyler/issues/73

changed_paths:
  maximum: 1000
  outcome: error

auto: false

commit_template: |
  Restyled by ${restyler.name}
pull_requests: true
comments: true

statuses: true

request_review:
  origin: author
  forked: none

restylers_version: stable

restylers:
  - 'prettier'
