name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
      - uses: actions/setup-node@v2.1.5

      - name: Install, Build
        run: |
          npm install
          npm run build
